spring:
  mvc:
    static-path-pattern: /static/**
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:media/ ,classpath:/static